DROP TABLE IF EXISTS richest;
CREATE TABLE richest(
  Ranking INT NOT NULL PRIMARY KEY,
  YearData INT,
  NameRich VARCHAR(38),
  Net_Worth_in_Billion_USD NUMERIC(9,6),
  Country VARCHAR(20)
);
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (1,2019,'Jeff Bezos',111,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (2,2019,'Bill Gates',108,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (3,2019,'Bernard Arnault',97.3,'France');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (4,2019,'Warren Buffett',83.8,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (5,2019,'Mark Zuckerberg',73.5,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (6,2019,'Amancio Ortega',68.3,'Spain');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (7,2019,'Larry Page',61.1,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (8,2019,'Charles Koch',60.8,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (9,2019,'Julia Flesher Koch',60.8,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (10,2019,'Larry Ellison',59.5,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (11,2019,'Sergey Brin',59.3,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (12,2019,'Francoise Bettencourt Meyers',58.2,'France');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (13,2019,'Carlos Slim',57.5,'Mexico');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (14,2019,'Mukesh Ambani',56.9,'India');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (15,2019,'Rob Walton',53.3,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (16,2019,'Steve Ballmer',53.1,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (17,2019,'Jim Walton',53.1,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (18,2019,'Alice Walton',52.2,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (19,2019,'Jacqueline Mars',42,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (20,2019,'John Mars',42,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (21,2019,'Jack Ma',41.6,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (22,2019,'Francois Pinault',37.3,'France');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (23,2019,'MacKenzie Bezos',35.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (24,2019,'Phil Knight',35.1,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (25,2019,'Sheldon Adelson',35,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (26,2019,'Pony Ma',33.2,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (27,2019,'Tadashi Yanai',31.7,'Japan');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (28,2019,'Michael Dell',31.1,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (29,2019,'Giovanni Ferrero',30.2,'Italy');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (30,2019,'Li Ka-Shing',28.2,'Hong Kong');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (31,2019,'Alain Wertheimer',27.6,'France');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (32,2019,'Gerard Wertheimer',27.6,'France');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (33,2019,'Hui Ka Yan',26.7,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (34,2019,'Vladimir Potanin',26.3,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (35,2019,'Elon R Musk',25.8,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (36,2019,'Len Blavatnik',25.6,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (37,2019,'Dieter Schwarz',25.3,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (38,2019,'Leonardo del Vecchio',24.7,'Italy');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (39,2019,'Lee Shau Kee',24.3,'Hong Kong');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (40,2019,'Leonid Mikhelson',23.9,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (41,2019,'Yang Huiyan',23.7,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (42,2019,'Laurene Powell Jobs',23.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (43,2019,'Jorge Paulo Lemann',22.6,'Brazil');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (44,2019,'Pallonji Mistry',22.4,'Ireland');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (45,2019,'Colin Huang',21.2,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (46,2019,'Elaine Marshall',21,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (47,2019,'Carl Icahn',20.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (48,2019,'Jim Simons',20.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (49,2019,'Leonard Lauder',20.6,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (50,2019,'Charoen Sirivadhanabhakdi',20.5,'Thailand');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (51,2019,'Vagit Alekperov',20.4,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (52,2019,'Stefan Persson',20.3,'Sweden');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (53,2019,'Azim Premji',20,'India');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (54,2019,'Susanne Klatten',19.7,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (55,2019,'He Xiangjian',19.3,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (56,2019,'Vladimir Lisin',19.2,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (57,2019,'Takemitsu Takizaki',18.8,'Japan');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (58,2019,'Jim Ratcliffe',18.7,'United Kingdom');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (59,2019,'Alexey Mordashov',18.5,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (60,2019,'Lukas Walton',18.5,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (61,2019,'Gennady Timchenko',18.2,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (62,2019,'Joseph Safra',18.1,'Brazil');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (63,2019,'Steve Schwarzman',17.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (64,2019,'Lee Kun Hee',17.7,'Korea, Republic of');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (65,2019,'Ernesto Bertarelli',17.2,'Switzerland');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (66,2019,'William Ding',17.1,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (67,2019,'Klaus-Michael Kuehne',16.9,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (68,2019,'Lui Che Woo',16.9,'Hong Kong');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (69,2019,'Ray Dalio',16.6,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (70,2019,'Abby Johnson',16.5,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (71,2019,'John Menard Jr',16.5,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (72,2019,'Heinz Hermann Thiele',16.5,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (73,2019,'Henry Cheng',16.4,'Hong Kong');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (74,2019,'Stefan Quandt',16.3,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (75,2019,'Donald Bren',16.2,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (76,2019,'Robert Kuok',16.2,'Malaysia');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (77,2019,'Shiv Nadar',16.1,'India');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (78,2019,'Lee Man Tat',15.9,'Hong Kong');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (79,2019,'Carl Cook',15.9,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (80,2019,'Gina Rinehart',15.8,'Australia');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (81,2019,'Alisher Usmanov',15.8,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (82,2019,'Budi Hartono',15.8,'Indonesia');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (83,2019,'Charlene de Carvalho-Heineken',15.7,'Netherlands');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (84,2019,'Thomas Peterffy',15.4,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (85,2019,'Roman Abramovich',15.3,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (86,2019,'Aliko Dangote',15.3,'Nigeria');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (87,2019,'Donald Newhouse',15,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (88,2019,'Iris Fontbona',15,'Chile');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (89,2019,'Wang Jianlin',14.8,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (90,2019,'Hasso Plattner',14.8,'Germany');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (91,2019,'Michael Hartono',14.8,'Indonesia');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (92,2019,'Eric Schmidt',14.7,'United States');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (93,2019,'Alwaleed Al Saud',14.5,'Saudi Arabia');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (94,2019,'Andrey Melnichenko',14.5,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (95,2019,'Viktor Vekselberg',14.2,'Russian Federation');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (96,2019,'Ricardo Salinas',14,'Mexico');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (97,2019,'Uday Kotak',13.9,'India');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (98,2019,'Masayoshi Son',13.9,'Japan');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (99,2019,'Zhang Zhidong',13.8,'China');
INSERT INTO richest(Ranking,YearData,NameRich,Net_Worth_in_Billion_USD,Country) VALUES (100,2019,'Sun Piaoyang',13.7,'China');